config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :create, :new, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [ :index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :create, :new, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name,:sku, :weight,:width,:height, :depth,:supplier_id, presence: true
  validates :weight, :width, :height, :depth, numericality: { greater_than: 0 }
  validates :sku, uniqueness: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @product_models = ProductModel.all
  end

  def new
    @suppliers = Supplier.all
    @product_model = ProductModel.new
  end

  def create
    
    product_model_params = params.require(:product_model).permit(:name, :sku,
                                :height,:width ,:depth , :weight, :supplier_id)
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to @product_model, notice: 'Produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o produto'
      render 'new'
    end
  end

  def show
    @product_model= ProductModel.find(params[:id])
  end


end

app/views/product_models/index.html.erb
<h1>Lista de Produtos </h1>

<%=  link_to 'Cadastrar Produto', new_product_model_path %>

<% if @product_models.any?%>
  <% @product_models.each do |pm| %> 
    <div>
      <h2> <%= pm.name %> </h2>
      <dl>
      <dt>Modelo:</dt>
      <dd><%= pm.sku  %></dd>
      <dt>Fornecedor:</dt>
      <dd><%= pm.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end%>
<% else %>
  <p>Não existem produtos cadastrados.</p>
<% end %>

app/views/product_models/new.html.erb
<h1> Cadastrar Produto </h1>


<% if(@product_model.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @product_model.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
  </ul>
<% end %>




<%= form_with(model: @product_model ) do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :sku %>
  <%= f.text_field :sku %>
  </div>

  <div>
  <%= f.label :weight %>
  <%= f.number_field :weight %>
  </div>

  <div>
  <%= f.label :width %>
  <%= f.number_field :width %>
  </div>

  <div>
  <%= f.label :height %>
  <%= f.number_field :height %>
  </div>

  <div>
  <%= f.label :depth %>
  <%= f.number_field :depth %>
  </div>

  <div>
  <%= f.label :supplier_id %>
  <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>

  <div>
  <%= f.submit 'Cadastrar' %>
  </div>
<% end%>

app/views/product_models/show.html.erb
<h1><%= @product_model.name%><h1>
<dl>
  <dt><strong>Fornecedor:</strong></dt>
  <dd><%= @product_model.supplier.brand_name %><br/></dd>

  <dt><strong>SKU:</strong></dt>
  <dd><%= @product_model.sku %><br/></dd>

  
  <dt><strong>Dimensões:</strong></dt>
  <dd><%= @product_model.height%>cm x
      <%= @product_model.width%>cm x
      <%= @product_model.depth%>cm<br/>
  </dd>

<dt><strong>Peso:</strong></dt>
  <dd><%= @product_model.weight %>g<br/></dd>
<dl>