config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :create, :new, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [ :index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :create, :new, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items

  enum status: {pending: 0, delivered:10, canceled:20}

  validates :deadline_delivery, :code, presence:true
  validate :estimated_delivery_date_is_future




  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.deadline_delivery.present? && self.deadline_delivery <= Date.today
      self.errors.add(:deadline_delivery, 'deve ser futura')
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_and_check_user, only: [:show,:edit,:update, :delivered, :canceled]

  def index
    @orders = current_user.orders
  end

  def new
    @suppliers = Supplier.all
    @warehouses = Warehouse.all
    @order = Order.new
  end

  def create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :deadline_delivery)
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      redirect_to @order , notice: 'Pedido registrado com sucesso'
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:alert] = 'Não foi possível criar a ordem de serviço'
      render 'new'
    end
  end

  def show
  end

  def search
    @code = params["query"]
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  def edit
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
  end

  def update
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :deadline_delivery)
    @order.update(order_params)
    redirect_to @order, notice: 'Pedido atualizado com sucesso'
  end

  def delivered
    @order.delivered!
    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create!(order: @order, product_model: item.product_model,warehouse:@order.warehouse)
      end
    end
    redirect_to @order
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end


  private

  def set_order_and_check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      return redirect_to root_path,notice: 'Erro! Página não encontrada'
    end
  end


end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |f| %>
<div>
  <%= f.label :warehouse_id %>
  <%= f.collection_select :warehouse_id,@warehouses, :id, :full_description %>
</div>
<div>
  <%= f.label :supplier_id %>
  <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
</div>
<div>
  <%= f.label :deadline_delivery %>
  <%= f.date_field :deadline_delivery %>
</div>
<%= f.submit 'Gravar' %>

<% end %>

app/views/orders/_order.html.erb
  <dl>
    <dt><%= Order.human_attribute_name(:code) %></dt>
    <dd><%= link_to order.code, order %></dd>
    <dt><strong> <%= Order.human_attribute_name(:warehouse_id)%>: </strong> </dt>
    <dd><%= order.warehouse.full_description %>  </dd>
    <dt><strong> <%= Order.human_attribute_name(:supplier_id)%>: </strong> </dt>
    <dd><%= order.supplier.brand_name  %></dd>
    <dt><strong><%= Order.human_attribute_name(:user_id)%>: </strong> </dt>
    <dd><%= order.user.name  %>  </dd>
    <dt><strong><%= Order.human_attribute_name(:deadline_delivery)%>: </strong> </dt>
    <dd> <%= order.deadline_delivery  %> </dd>
     <dt><strong><%= Order.human_attribute_name(:status)%>: </strong> </dt>
    <dd> <%= I18n.t(order.status)  %> </dd>
  </dl>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Meus Pedidos: </h1>

<% @orders.each do |order| %>
  <%= render order  %>
<% end %>

app/views/orders/new.html.erb
<h1> Registrar pedido </h1>


<% if(@order.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
  </ul>
<% end %>


<%= render 'form' %>

app/views/orders/search.html.erb
<h1> Resultados da busca por: <%= @code %> </h1>

<p><%=@orders.count%> <%= Order.model_name.human(count:@orders.count)%> <%=I18n.t(:found,count: @orders.count)%> </p>
<% @orders.each do |order| %>
    <%= render order %>
  <% end %>

app/views/orders/show.html.erb
<h1>Detalhes do Pedido:</h1>
<h2> <%= Order.model_name.human %> <%= @order.code %> </h2>

<dl>
  <dt> <%= Order.human_attribute_name(:warehouse_id)%>:</dt>
  <dd><%= @order.warehouse.full_description %></dd>
  <dt> <%= Order.human_attribute_name(:supplier_id)%>: </dt>
  <dd><%= @order.supplier.brand_name %> </dd>
  <dt> <%= Order.human_attribute_name(:user_id)%>:</dt>
  <dd><%= @order.user.description %> </dd>
  <dt>  <%= Order.human_attribute_name(:deadline_delivery)%>:</dt>
  <dd><%= I18n.localize(@order.deadline_delivery) %> </dd>
  <dt><strong><%= Order.human_attribute_name(:status)%>: </strong> </dt>
  <dd> <%= I18n.t(@order.status)  %> </dd>
</dl>


<h2>Itens do pedido:</h2>
<% @order.order_items.each do |item| %>
  <%=item.quantity %> x <%= item.product_model.name %><br/>
<% end %>

<%= link_to 'Adicionar item', new_order_order_item_path(@order, @order.id) %>

<% if @order.pending? %>
  <%= button_to 'Marcar como Entregue', delivered_order_path(@order) %>
  <%= button_to 'Marcar como Cancelado', canceled_order_path(@order) %>
<% end %>
<%= link_to 'Editar', edit_order_path(@order.id)%>