config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :create, :new, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [ :index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :create, :new, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :company_name, :company_register, :brand_name, :adress, :city,
            :state, :email, :phone_number, presence: true
  validates :company_register, uniqueness: true
  validates :company_register, length: {is: 18}
  validates :company_register, format: 
            { with: /\A\d{2}\.\d{3}\.\d{3}\/000[1-2]-\d{2}\z/}
  validates :phone_number, length: {is: 12} 
  validates :phone_number, format: { with: /\A\d{7}-\d{4}\z/}

  has_many :product_models
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
      if @supplier.save
        redirect_to suppliers_path, notice: 'Fornecedor cadastrado com sucesso!'
      else
        flash.now[:alert] = 'Erro! Fornecedor não cadastrado.'
        render 'new'
      end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    if @supplier.update(supplier_params)
      return redirect_to supplier_path(@supplier.id), notice:'Fornecedor atualizado com sucesso'
    else 
      flash.now[:notice] = 'Não foi possível atualizar o fornecedor'
      render 'edit'
    end
  end

  private 

  def supplier_params
    params.require(:supplier).permit(:company_name, :company_register, 
           :brand_name, :adress, :city, :state, :email, :phone_number)
  end

end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :company_name  %>
    <%= f.text_field :company_name %>
  </div>

  <div>
    <%= f.label :company_register %>
    <%= f.text_field :company_register %>
  </div>

  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>

  <div>
    <%= f.label :adress %>
    <%= f.text_field :adress %>
  </div>

<div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div> 
    <%= f.submit 'Cadastrar' %>
  </div>

<% end %>

app/views/suppliers/edit.html.erb
<h1> Editar Fornecedor </h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Lista de fornecedores:</h1>
  <div>
    <%= link_to('Cadastrar novo fornecedor', new_supplier_path) %>
  </div>
<% if @suppliers.any?%>
    <table>
      <thead>
        <tr>
          <th> Nome</th>
          <th> Localização</th>
        </tr>
        </thead>
        <tbody>
          <% @suppliers.each do |s| %>
            <tr>
            <td> <%= link_to s.brand_name, s  %></td>
            <td> <%= s.city %> - <%= s.state %> </td>
           </tr>
          <% end %>
        <tbody>
      </table>
<% else %>
  <p> Não existem fornecedores cadastrados.</p>
<% end %>

app/views/suppliers/new.html.erb
<h1>Cadastrar novo fornecedor</h1>

<% if(@supplier.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1> Detalhes sobre o fornecedor:<%= @supplier.brand_name%> </h1>
<h2> <%= @supplier.company_name  %> </h2>

<dl>
  <dt><strong>CPNJ:</strong></dt>
    <dd><%= @supplier.company_register %><br/></dd>

  <dt><strong>Endereço:</strong></dt>
    <dd><%= @supplier.adress %> - <%= @supplier.city %> - <%= @supplier.state %> <br/></dd>

  <dt><strong>E-mail:</strong></dt>
    <dd><%= @supplier.email %> <br/></dd>

  <dt><strong>Telefone:</strong></dt>
    <dd><%= @supplier.phone_number %> <br/></dd>
</dl>

<div>
<%= link_to('Editar', edit_supplier_path(@supplier.id))%>
</div>

<div>
<%= link_to('Voltar', suppliers_path)%> <br/>
</div>