config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :create, :new, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [ :index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :create, :new, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1> Galpões & Estoque </h1>
      <nav>
        <%= link_to 'Home', root_path %> | 
         <%= link_to 'Meus Pedidos', orders_path %>
        <% if user_signed_in? %>
          <%= current_user.description %> |
            <%=form_with(url: search_orders_path, method: :get) do |f| %>
            <%= f.label :query, 'Rastrear pedido' %>:
            <%= f.text_field :query%>
            <%= f.submit 'Buscar' %>
    <% end%>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %> 
        <% else %>
          <%= link_to 'Entrar',  new_user_session_path %> | <br/>
        <% end %>
        <%= link_to 'Fornecedores', suppliers_path %> |
        <%= link_to 'Lista de Produtos', product_models_path %>
        <%= link_to 'Registrar pedido', new_order_path %>
      </nav>
    </header>
    <main>
  <div style = "margin:10px 0px" >
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
    <%= yield %>
    </main>
  </body>
</html>